version: '3.8'

services:
  mysql:
    image: mysql:8.0.39-debian
    container_name: mysql_db
    volumes:
      - ./.mysqldata/:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - ams

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: development
    container_name: backend_app
    env_file:
      - .env
    ports:
      - ${API_PORT:-8002}:8000
      - ${DEBUG_PORT:-9002}:5678
    restart: on-failure
    volumes:
      - ./.logs/backend/:/app/.logs/
    depends_on:
      - mysql
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - ./backend/.git
            - ./backend/.vscode
            - ./backend/.idea
            - ./backend/.venv
            - ./backend/.pgdata
            - ./backend/.mypy_cache
            - ./backend/.github
            - ./backend/.ruff_cache
            - ./backend/.dockerignore
            - ./backend/.gitignore
        - action: rebuild
          path: ./backend/pyproject.toml
        - action: rebuild
          path: .env
    networks:
      - ams

  # frontend:
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   container_name: frontend_app
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #   restart: on-failure
  #   volumes:
  #     - ./frontend/:/app
  #   depends_on:
  #     - backend
  #   networks:
  #     - abs

  nginx:
    image: nginx:1.27.0
    container_name: nginx_proxy
    depends_on:
      - mysql
      # - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.logs/nginx/:/var/log/nginx/
    ports:
      - 80:80
    networks:
      - ams

networks:
  ams:
    driver: bridge
